version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
    - :80
    - :50000
    volumes:
    - ./volumes/master:/var/jenkins_home
    environment:
    - JAVA_OPTS="-Dhudson.model.DirectoryBrowserSupport.CSP="