# /a/b/c 
version: "3"
services:
  nginx:
    image: nginx
  alpine:
    image: alpine
    entrypoint: "wget http://nginx"
    depends_on:
    - nginx
    working_dir: /a/b/c
    volumes:
    - ./vol:/a/b/c